[ENTESB-14875] Avoid manual server pod respin
syndesisio/syndesis-qe pull request #1711
Opened 2021-02-19 12:58 UTC by jsafarik

//test: `@ENTESB-14875`

2021-02-19 13:35 UTC, syndesisqe commented
Build finished. Tests PASSED

2021-02-22 07:47 UTC, avano requested changes, later dismissed

2021-02-22 07:47 UTC, avano commented on operator-tests/src/test/java/io/syndesis/qe/OperatorValidationSteps.java
> +    private String getCrFromFileAsString(String file) throws IOException {
rather `fail` than `throws`

2021-02-22 07:47 UTC, avano commented on operator-tests/src/test/java/io/syndesis/qe/OperatorValidationSteps.java
> +
remove one empty line

2021-02-22 11:48 UTC, avano approved these changes

2021-02-22 12:16 UTC, syndesisqe commented
Build finished. Tests PASSED

2021-02-22 12:16 UTC, merged

2021-02-22 12:28 UTC, syndesisqe commented
Following scenarios failed:
```
Integration - Database | Smoke - Periodic invocation to Insert 
```