[FUSEQE-12454] - tests for auditing
syndesisio/syndesis-qe pull request #1748
Opened 2021-05-04 08:32 UTC by mkralik3

//test: `@auditing`

2021-05-04 09:32 UTC, syndesisqe commented
Following scenarios failed:
```
Test auditing feature | Test auditing on API connector 
Test auditing feature | Test auditing on integration 
Test auditing feature | Test auditing on oauth 
```

2021-05-04 10:02 UTC, syndesisqe commented
Following scenarios failed:
```
Integration - Database | Smoke - Periodic invocation to Insert 
Connection - CRUD | Create and delete 
Connection - CRUD | Kebab menu 
Connection - CRUD | Kebab menu edit and view 
Integration - DB to DB | Read and update operations 
Test auditing feature | Test auditing on API connector 
Test auditing feature | Test auditing on connection 
Test auditing feature | Test auditing on integration 
Test auditing feature | Test auditing on oauth 
Integration info | Check error for integration with the same name 
Integration info | Check error for integration which has same name after update 
```

2021-05-04 13:33 UTC, mkralik3 commented
retest this please

2021-05-04 13:55 UTC, avano requested changes, later dismissed

2021-05-04 13:55 UTC, avano commented on operator-tests/src/test/resources/operator/spec/auditing.yml
> +apiVersion: syndesis.io/v1beta2
this file should be in `spec/components/server/`

2021-05-04 15:04 UTC, syndesisqe commented
Following scenarios failed:
```
Test auditing feature | Test auditing on API connector 
Test auditing feature | Test auditing on connection 
```

2021-05-04 17:37 UTC, syndesisqe commented
Following scenarios failed:
```
Test auditing feature | Test auditing on integration 
```

2021-05-05 07:29 UTC, avano approved these changes

2021-05-05 07:59 UTC, mkralik3 commented
retest this please

2021-05-07 12:35 UTC, mkralik3 commented
retest this please

2021-05-07 13:19 UTC, syndesisqe commented
Build finished. Tests PASSED

2021-05-07 13:19 UTC, merged